[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$memoryRoot = Join-Path $repoRoot '.serena\memories\shared'
$outputDirectory = Join-Path $repoRoot '.Temp'
$outputPath = Join-Path $outputDirectory 'serena-memory.md'

if (-not (Test-Path -LiteralPath $memoryRoot)) {
    throw "Shared Serena memory directory is missing: $memoryRoot"
}

$sources = Get-ChildItem -Path $memoryRoot -Filter '*.md' -File |
    Sort-Object Name
if ($sources.Count -eq 0) {
    throw "No shared Serena memories found in: $memoryRoot"
}

New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('# Combined Shared Serena Memory')
[void]$builder.AppendLine()
[void]$builder.AppendLine('Generated by `tools/governance/serena/combine-serena-shared.ps1`; context only.')

foreach ($source in $sources) {
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("<!-- source: .serena/memories/shared/$($source.Name) -->")
    [void]$builder.AppendLine((Get-Content -LiteralPath $source.FullName -Raw).TrimEnd())
    [void]$builder.AppendLine()
}

[IO.File]::WriteAllText($outputPath, $builder.ToString(), [Text.UTF8Encoding]::new($false))
Write-Output "Generated $outputPath from $($sources.Count) shared Serena memories."
