[CmdletBinding()]
param()

if ($PSVersionTable.PSVersion.Major -lt 7) {
    Write-Error "PowerShell 7 or newer is required. Current version: $($PSVersionTable.PSVersion). Run this script with pwsh.exe."
    exit 1
}

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$outputDirectory = Join-Path $repoRoot '.Temp'
$outputPath = Join-Path $outputDirectory 'all-agents-combined.md'
$sources = @(
    (Join-Path $repoRoot 'AGENTS.md'),
    (Join-Path $repoRoot '.github\AGENTS.md')
)

$sources += Get-ChildItem -Path (Join-Path $repoRoot '.github\agents') -Filter '*.agent.md' -File |
    Sort-Object FullName |
    Select-Object -ExpandProperty FullName
$skillsRoot = Join-Path $repoRoot '.agents\skills'
if (Test-Path -LiteralPath $skillsRoot) {
    $sources += Get-ChildItem -Path $skillsRoot -Filter 'SKILL.md' -File -Recurse |
        Sort-Object FullName |
        Select-Object -ExpandProperty FullName
}

foreach ($source in $sources) {
    if (-not (Test-Path -LiteralPath $source)) {
        throw "Required governance source is missing: $source"
    }
}

function Get-AgentMetadata {
    param([System.IO.FileInfo]$Source)

    $lines = Get-Content -LiteralPath $Source.FullName
    if ($lines.Count -lt 3 -or $lines[0] -ne '---') {
        throw "Agent frontmatter is missing in: $($Source.FullName)"
    }
    $endIndex = [Array]::IndexOf($lines, '---', 1)
    if ($endIndex -lt 0) {
        throw "Agent frontmatter is not closed in: $($Source.FullName)"
    }

    $metadata = @{}
    for ($index = 1; $index -lt $endIndex; $index++) {
        if ($lines[$index] -match '^([A-Za-z][A-Za-z-]*):\s*(.*)$') {
            $metadata[$Matches[1]] = $Matches[2]
        }
    }
    foreach ($required in @('name', 'description', 'model', 'tools', 'agents', 'user-invocable', 'disable-model-invocation', 'handoffs')) {
        if (-not $metadata.ContainsKey($required)) {
            throw "Agent frontmatter field '$required' is missing in: $($Source.FullName)"
        }
    }
    if ($metadata['user-invocable'] -notin @('true', 'false') -or
        $metadata['disable-model-invocation'] -notin @('true', 'false')) {
        throw "Agent frontmatter booleans are invalid in: $($Source.FullName)"
    }
    if ($metadata.tools -notmatch '^\[.*\]$' -or $metadata.agents -notmatch '^\[.*\]$') {
        throw "Agent frontmatter lists are invalid in: $($Source.FullName)"
    }
    $handoffAgents = @($lines[1..($endIndex - 1)] |
            Where-Object { $_ -match '^\s+agent:\s*([A-Za-z0-9-]+)\s*$' } |
            ForEach-Object { $Matches[1] })
    return [PSCustomObject]@{
        Path = [IO.Path]::GetRelativePath($repoRoot, $Source.FullName).Replace('\', '/')
        Name = $metadata.name
        Tools = $metadata.tools
        UserInvocable = $metadata['user-invocable']
        ModelInvocationDisabled = $metadata['disable-model-invocation']
        Agents = $metadata.agents
        Handoffs = if ($handoffAgents.Count -gt 0) { $handoffAgents -join ', ' } else { $metadata.handoffs }
    }
}

New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('# Combined Agent Governance')
[void]$builder.AppendLine()
[void]$builder.AppendLine('Generated by `tools/governance/combine-agent-md.ps1`; do not commit this file.')
[void]$builder.AppendLine()
[void]$builder.AppendLine('## Source Manifest')
[void]$builder.AppendLine()
[void]$builder.AppendLine('| Source | Name | Tools | User-invocable | Model invocation disabled | Agent approvals | Handoffs |')
[void]$builder.AppendLine('| --- | --- | --- | --- | --- | --- | --- |')

$agentSources = Get-ChildItem -Path (Join-Path $repoRoot '.github\agents') -Filter '*.agent.md' -File |
    Sort-Object FullName
foreach ($agentSource in $agentSources) {
    $metadata = Get-AgentMetadata -Source $agentSource
    [void]$builder.AppendLine("| $($metadata.Path) | $($metadata.Name) | $($metadata.Tools) | $($metadata.UserInvocable) | $($metadata.ModelInvocationDisabled) | $($metadata.Agents) | $($metadata.Handoffs) |")
}
[void]$builder.AppendLine()
[void]$builder.AppendLine("Sources: $($sources.Count) governance files; $($agentSources.Count) agents with validated frontmatter.")

foreach ($source in $sources) {
    $relativePath = [IO.Path]::GetRelativePath($repoRoot, $source).Replace('\', '/')
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("<!-- source: $relativePath -->")
    [void]$builder.AppendLine((Get-Content -LiteralPath $source -Raw).TrimEnd())
    [void]$builder.AppendLine()
}

[IO.File]::WriteAllText($outputPath, $builder.ToString(), [Text.UTF8Encoding]::new($false))
Write-Output "Generated $outputPath from $($sources.Count) governance sources."
