[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$outputDirectory = Join-Path $repoRoot '.Temp'
$outputPath = Join-Path $outputDirectory 'all-agents-combined.md'
$sources = @(
    (Join-Path $repoRoot 'AGENTS.md'),
    (Join-Path $repoRoot '.github\AGENTS.md')
)

$sources += Get-ChildItem -Path (Join-Path $repoRoot '.github\agents') -Filter '*.agent.md' -File |
    Sort-Object FullName |
    Select-Object -ExpandProperty FullName
$skillsRoot = Join-Path $repoRoot '.agents\skills'
if (Test-Path -LiteralPath $skillsRoot) {
    $sources += Get-ChildItem -Path $skillsRoot -Filter 'SKILL.md' -File -Recurse |
        Sort-Object FullName |
        Select-Object -ExpandProperty FullName
}

foreach ($source in $sources) {
    if (-not (Test-Path -LiteralPath $source)) {
        throw "Required governance source is missing: $source"
    }
}

New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('# Combined Agent Governance')
[void]$builder.AppendLine()
[void]$builder.AppendLine('Generated by `tools/governance/combine-agent-md.ps1`; do not commit this file.')

foreach ($source in $sources) {
    $relativePath = [IO.Path]::GetRelativePath($repoRoot, $source).Replace('\', '/')
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("<!-- source: $relativePath -->")
    [void]$builder.AppendLine((Get-Content -LiteralPath $source -Raw).TrimEnd())
    [void]$builder.AppendLine()
}

[IO.File]::WriteAllText($outputPath, $builder.ToString(), [Text.UTF8Encoding]::new($false))
Write-Output "Generated $outputPath from $($sources.Count) governance sources."
